---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Default: pathways-dev-mm-app-svc-namespace

  NamespaceName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  PrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: Cloud Map private DNS namespace for resources for example.com website
      Vpc: !Ref VpcId
      Name: !Ref NamespaceName

Outputs:
  PrivateDnsNameSpace:
    Value: !Ref PrivateDnsNamespace
    Export: { "Name" : !Ref Name }      
