---
AWSTemplateFormatVersion: 2010-09-09

Description: This is a parent template for an application environment to implement all the AWS resources required i.e. ECS Cluster and associated Load Balancer.

Parameters:
  TemplateBucket:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack.

  EnvironmentInstance:
    Type: String

  StackName:
    Type: String

  VpcCIDR:
    Type: String

  DMZSubnet1CIDR:
    Type: String

  DMZSubnet2CIDR:
    Type: String

  ECSSubnet1CIDR:
    Type: String

  ECSSubnet2CIDR:
    Type: String

  ECSSubnet3CIDR:
    Type: String

  ServicesSubnet1CIDR:
    Type: String

  ServicesSubnet2CIDR:
    Type: String

  ServicesSubnet3CIDR:
    Type: String

  RDSSubnet1CIDR:
    Type: String

  RDSSubnet2CIDR:
    Type: String

  RDSSubnet3CIDR:
    Type: String

  MongoSubnet1CIDR:
    Type: String

  MongoSubnet2CIDR:
    Type: String

  MongoSubnet3CIDR:
    Type: String

  NamespaceName:
    Type: String

Resources:

  RootCA:
    Type: 'AWS::ACMPCA::CertificateAuthority'
    Properties:
      Type: ROOT
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        Country: UK
        Organization: MoJ
        OrganizationalUnit: YJB
        State: London
        CommonName: '*.dev.yjb.com'
        Locality: London
      RevocationConfiguration:
        CrlConfiguration:
          Enabled: false
  RootCACertificate:
    Type: 'AWS::ACMPCA::Certificate'
    Properties:
      CertificateAuthorityArn: !Ref RootCA
      CertificateSigningRequest: !GetAtt 
        - RootCA
        - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      TemplateArn: 'arn:aws:acm-pca:::template/RootCACertificate/V1'
      Validity:
        Type: DAYS
        Value: 100
  RootCAActivation:
    Type: 'AWS::ACMPCA::CertificateAuthorityActivation'
    Properties:
      CertificateAuthorityArn: !Ref RootCA
      Certificate: !GetAtt 
        - RootCACertificate
        - Certificate
      Status: ACTIVE

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/network/VPC/vpc.yaml"
      Tags:
        - Key: owner
          Value: nps
        - Key: EnvironmentInstance
          Value: !Ref EnvironmentInstance
        - Key: capability
          Value: network
        - Key: components
          Value: VPC
        - Key: source-code
          Value: na
        - Key: application
          Value: any
        - Key: service
          Value: compute
        - Key: is-production
          Value: no
        - Key: runbook-description-confluence-url
          Value: no
        - Key: infrastructure-support
          Value: devops
      Parameters:
        Name: !Ref StackName
        VpcCIDR: !Ref VpcCIDR

  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/network/subnets/subnets.yaml"
      Tags:
        - Key: owner
          Value: nps
        - Key: EnvironmentInstance
          Value: !Ref EnvironmentInstance
        - Key: capability
          Value: network
        - Key: components
          Value: VPC
        - Key: source-code
          Value: na
        - Key: application
          Value: any
        - Key: service
          Value: networking
        - Key: is-production
          Value: no
        - Key: runbook-description-confluence-url
          Value: no
        - Key: infrastructure-support
          Value: devops
      Parameters:
        Name: !Ref StackName
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt VPC.Outputs.InternetGatewayId
        EgressInternetGatewayId: !GetAtt VPC.Outputs.EgressInternetGatewayId
        DMZSubnet1CIDR: !Ref DMZSubnet1CIDR
        DMZSubnet2CIDR: !Ref DMZSubnet2CIDR
        ECSSubnet1CIDR: !Ref ECSSubnet1CIDR
        ECSSubnet2CIDR: !Ref ECSSubnet2CIDR
        ECSSubnet3CIDR: !Ref ECSSubnet3CIDR
        ServicesSubnet1CIDR: !Ref ServicesSubnet1CIDR
        ServicesSubnet2CIDR: !Ref ServicesSubnet2CIDR
        ServicesSubnet3CIDR: !Ref ServicesSubnet3CIDR
        RDSSubnet1CIDR: !Ref RDSSubnet1CIDR
        RDSSubnet2CIDR: !Ref RDSSubnet2CIDR
        RDSSubnet3CIDR: !Ref RDSSubnet3CIDR
        MongoSubnet1CIDR: !Ref MongoSubnet1CIDR
        MongoSubnet2CIDR: !Ref MongoSubnet2CIDR
        MongoSubnet3CIDR: !Ref MongoSubnet3CIDR

  Route53:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/services/route53/private-dns-zone.yaml"
      Tags:
        - Key: owner
          Value: nps
        - Key: EnvironmentInstance
          Value: !Ref EnvironmentInstance
        - Key: capability
          Value: network
        - Key: components
          Value: VPC
        - Key: source-code
          Value: na
        - Key: application
          Value: any
        - Key: service
          Value: networking
        - Key: is-production
          Value: no
        - Key: runbook-description-confluence-url
          Value: no
        - Key: infrastructure-support
          Value: devops
      Parameters:
        Name: !Ref StackName
        VpcId: !GetAtt VPC.Outputs.VpcId
        NamespaceName: !Ref NamespaceName

 