---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Default: pathways-dev-mm-app-svc-namespace

  NamespaceName:
    Type: String

Resources:
  PrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: Cloud Map private DNS namespace for resources for example.com website
      Vpc: { "Fn::ImportValue" : "pathways-dev-vpc-id" }
      Name: !Ref NamespaceName

  PrivDnsNsSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref NamespaceName
      Type: String
      Value: !Ref PrivateDnsNamespace
      Description: Creating an SSM parameter for Route53 Hosted Zone.
      Tags:
        Environment: !Ref NamespaceName

Outputs:
  PrivateDnsNameSpace:
    Value: !Ref PrivateDnsNamespace
    Export: { "Name" : !Ref Name }      
