---
AWSTemplateFormatVersion: 2010-09-09

Description: This is a parent template for an application environment to implement all the AWS resources required for mongo.

Parameters:
  TemplateBucket:
    Type: String

  EnvironmentInstance:
    Type: String

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Type: AWS::EC2::VPC::Id

  VPCLambdaSubnets:
    Description: Subnets which required RDS to be deployed
    Type: List<AWS::EC2::Subnet::Id>

  VPCSecurityGroups:
    Description: List of SecurityGroup for the VPC to refine database access
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:

  Accounts:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/services/mongo/mongodb-accounts.yaml"
      Parameters:
        EnvironmentInstance: !Ref EnvironmentInstance

  MongoManagerLamdbda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/services/mongo/mongodb-lambda-deploy.yaml"
      Parameters:
        EnvironmentInstance: !Ref EnvironmentInstance
        VPCSecurityGroups: !Ref VPCSecurityGroups
        VPCLambdaSubnets: !Ref VPCLambdaSubnets
        TemplateBucket: !Ref TemplateBucket

  MongoNode:
    DependsOn:
      - Accounts
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/services/mongo/mongodb-single-node.yaml"
      Parameters:
        RootValueUsername:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoRootSecretUsername
        RootValuePassword:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoRootSecretPassword

        AdminValueUsername:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoAdminSecretUsername

        AdminValuePassword:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoAdminSecretPassword

        ApplicationValueUsername:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoApplicationSecretUsername

        ApplicationValuePassword:
          Fn::Sub:
            - ${value1}
            - value1: !GetAtt Accounts.Outputs.MongoApplicationSecretPassword

        VpcId: !Ref VpcId
        SubnetId: !Ref SubnetId
        EnvironmentInstance: !Ref EnvironmentInstance