---
AWSTemplateFormatVersion: 2010-09-09

Description: Create a certificate and activate the CA.

RootInternalCert:
 Type: AWS::ACMPCA::Certificate
 Properties:
  CertificateAuthorityArn: !Ref RootInternalCA
  CertificateSigningRequest: !GetAtt RootInternalCA.CertificateSigningRequest
  SigningAlgorithm: SHA512WITHRSA
  TemplateArn: 'arn:aws:acm-pca:::template/RootCACertificate/V1'
  Validity:
    Type: YEARS
    Value: 10

RootCAActivation:
 Type: 'AWS::ACMPCA::CertificateAuthorityActivation'
 Properties:
  CertificateAuthorityArn: !Ref RootInternalCA
  Certificate: !GetAtt RootInternalCert.Certificate
  Status: ACTIVE