AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template RDS_with_DBParameterGroup

            Required Parameters:
               dbName
               dbUsername
               dbPassword
               VPC Subnet/s
               VPC security groups'

Parameters:
  DBName:
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.

  VPCPrivateSubnets:
    Description: Subnets which required RDS to be deployed
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: must contain only subnets.

  VPCSecurityGroups:
    Description: List of SecurityGroup for the VPC to refine database access
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: must contain only list of VPC Security Groups.

  EnvironmentInstance:
    Type: String
    Default: DEV

Resources:
  RDSRootSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS encrypted credential; randomly generated JSON.'
      GenerateSecretString:
      SecretStringTemplate: '{"username": "postgres"}'
      GenerateStringKey: 'password'
      PasswordLength: 50
      Name:
        'Fn::Join':
          - ''
          - - 'rdsRootAccount'
            - 'Fn::Transform':
                Name: Cap
                Parameters:
                  InputString: !Ref EnvironmentInstance
                  Operation: Capitalize
      ExcludeCharacters: '"@/\'
    Tags:
      - Key: env
        Value: !Ref EnvironmentInstance

  RDSlambdaSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS encrypted credential; randomly generated JSON.'
      GenerateSecretString:
      SecretStringTemplate: '{"username": "postgres"}'
      GenerateStringKey: 'password'
      PasswordLength: 50
      Name:
        'Fn::Join':
          - ''
          - - 'rdslambdaAccount'
            - 'Fn::Transform':
                Name: Cap
                Parameters:
                  InputString: !Ref EnvironmentInstance
                  Operation: Capitalize
      ExcludeCharacters: '"@/\'
    Tags:
      - Key: env
        Value: !Ref EnvironmentInstance

  RDSApplicationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS encrypted credential; randomly generated JSON.'
      GenerateSecretString:
      SecretStringTemplate: '{"username": "postgres"}'
      GenerateStringKey: 'password'
      PasswordLength: 50
      Name:
        'Fn::Join':
          - ''
          - - 'rdsApplicationAccount'
            - 'Fn::Transform':
                Name: Cap
                Parameters:
                  InputString: !Ref EnvironmentInstance
                  Operation: Capitalize
      ExcludeCharacters: '"@/\'
    Tags:
      - Key: env
        Value: !Ref EnvironmentInstance

  DEVDBSubnet:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      DBSubnetGroupName: RDSSubnetGroup
      SubnetIds: !Ref VPCPrivateSubnets
      Tags:
        - Key: EnvironmentInstance
          Value: !Ref EnvironmentInstance

  DEVDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 14
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: !Ref DBName
      DBName: !Ref DBName
      DeleteAutomatedBackups: true
      DeletionProtection: false
      EnableIAMDatabaseAuthentication: true
      EnablePerformanceInsights: true
      Engine: Postgres
      EngineVersion: 11
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSRootSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSRootSecret, ':SecretString:password}}' ]]
      MultiAZ: false
      DBSubnetGroupName: !Ref DEVDBSubnet
      OptionGroupName: default:postgres-11
      Port: 5432
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: standard
      Tags:
        - Key: EnvironmentInstance
          Value: !Ref EnvironmentInstance
      VPCSecurityGroups: !Ref VPCSecurityGroups

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', [      'jdbc:postgresql://', !GetAtt [DEVDB, Endpoint.Address], ':', !GetAtt [
      DEVDB, Endpoint.Port], /, !Ref 'DBName']]
    Export: { "Name": !Join ['', ['JDBCConnectionString', '-', !Ref EnvironmentInstance]]}

  DBNameString:
    Description: JDBC connection string for the database
    Value: !Ref DBName
    Export: { "Name": !Join ['', ['DBName', '-', !Ref EnvironmentInstance]]}
